### PR TITLE
Create a new schedule page for FOSDEM '24

### PR DESCRIPTION
**Pull request by NPDebs**
This PR serves the purpose of including the schedule information for FOSDEM 2024, readily providing attendees and organisers with easy access to the online event's schedule.

**Changes made:**
- Created a new Markdown (.md) file `2024-online-schedule.md`.
- Added the schedule information for the online event, in a tabular form.

**Screenshots below:**

Thank you for the review!

### CODE REVIEW

**Review by yochannah — COMMENTED** [review]
Thanks Debs! 

This looks great! One small question: The proposal text looks a little long to me - should we keep it, or might things get tidier if we removed it? 🙏

**Comment by NPDebs** [comment]
> One small question: The proposal text looks a little long to me - should we keep it, or might things get tidier if we removed it? 🙏 

Thanks, Yo! 🌷
To your question, yes, I did feel it was a bit too long.

We have **two options** though.
1. Make it wider, by reducing the width of some other shorter columns.
2. Remove it entirely.

I would favour option 1, because 2 means anyone looking at the schedule won't know what each talk is about. 

I guess that brings us to a third option — increase the width and reduce the content of the proposal as much as sensibly possible.

Apologies if I have made it a harder decision. 😆

**Comment by yochannah** [comment]
😂  Thanks Debs. 

I agree, the talk long descriptions are helpful. 

How about this - remove them for now - and then I'll merge the PR, then in a separate PR, add the long description at the end, and link with internal hyperlinks? 

This gives us 1. the schedule-at-a-glance for people attending on the day and 2. still keeps the descriptions.

**Comment by NPDebs** [comment]
Sounds good. I'm on it! 🕺🏽

**Comment by NPDebs** [comment]
Yo, question...don't we need to link to this schedule page from the `/home` page? 😀

**Comment by yochannah** [comment]
yes please! 🙏

**Comment by yochannah** [comment]
thanks! I've pinged the team to merge or add me as aperson who can merge.

**Pull request merged**
